### DISCUSSION TITLE
Changing color of nodes

### DISCUSSION THREAD

**Discussion by OutLandishnessSad** [newcat/baklavajs#205] [Q&A] [answered]
Hey there, am not really great programmer but i would like to change color some types of nodes.. is there any way how to do it ? Best would be to split nodes into groups and each group would have different color. Am using VueJS_v.2.9.6 and quasar v.3.2.9.

**Comment by newcat** [comment, marked as answer]
You can use CSS for that, by creating classes for your node type. Let's say you have a `AdditionNode` and a `SubtractionNode`, which you want to color green, as well as a `DisplayNode` which you want to be red:

```css
.node.--type-AdditionNode,
.node.--type-SubtractionNode {
  background: green;
}

.node.--type-DisplayNode {
  background: red;
}
```

**Reply by OutLandishnessSad** [reply]
Thank you so much !! And is there any way how to change header color ? In basic its black with name of the node :)

**Reply by newcat** [reply]
Yes :+1:
```css
.node > .__title {
  background: blue;
}

.node.--type-DisplayNode > .__title {
  background: red;
}
```
