### ISSUE TITLE
Customizing background color

### ISSUE THREAD

**Issue by pixldev** [newcat/baklavajs#58]
Hello, is it possible? If yes, how?

**Comment by newcat** [comment]
Yup, you can add this CSS snippet:
```css
.node-editor {
    background-color: lightskyblue !important;
    background-image: none !important;
}
```
