### ISSUE TITLE
Choose side of inputs/outputs

### ISSUE THREAD

**Issue by tpoxa** [newcat/baklavajs#69]
Is it possible to set which side will be used for output or input?
I would like to have outputs and inputs positioned on the same side for some of my nodes.
Thanks.

**Comment by tpoxa** [comment]
And I guess as soon as inputs and outputs will be placed on the same side, we need to think about how to differ them.  Maybe with. -< or >- symbols.

**Comment by newcat** [comment]
With [v1.6.0](https://github.com/newcat/baklavajs/releases/tag/v1.6.0) you should be able to do this by adding the following CSS, which will move the input interfaces to the right side of the node:

```css
.node.--type-MathNode .node-interface.--input {
    text-align: right;
    padding-left: unset;
    padding-right: 0.5em;
}

.node.--type-MathNode .node-interface.--input > .__port {
    left: unset;
    right: -1.1em;
}
```

In your case you'd have to replace the `.--type-MathNode` with the type of node you actually want to change. Using CSS you can also restyle the ports so that they have a triangle shape instead of a circle. You can use the [original styling](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-renderer-vue/src/styles/node-editor/node-interface.scss) as a baseline to customize your styles.
